### ISSUE TITLE
Tutorial 1 itp files missing

### ISSUE THREAD

**Issue by santamaria42** [subhamoymahajan/Martini_PEI_ff#2]
# Description
The files:
martini_v2.0_ions.itp
martini_v2.2refP.itp
martini_v2.2refP_constr.itp

are not included in the repository and need to be copied manually into the install directory for the program to work. It would be nice if they could come with the repository.
I also no not know what is supposed to be in "martini_v2.2refP_constr.itp" and just copied "martini_v2.2refP.itp" to get the program to work.

**Comment by subhamoymahajan** [comment]
The files do not have a copyright statement, so I cannot share them here. The key difference between "martini_v2.2refP.itp" and "martini_v2.2refP_constr.itp" is to convert the "constraints" in polarizable water to harmonic bonds during minimization as suggested in the commented lines in (martini_v2.2refP.itp").

**Comment by santamaria42** [comment]
Thank you for the explanation. 
Maybe you could add this information to the README.md as well as a note that the program needs Python3.7 since there seems to be an issue with networkx in the llatest Python version where "write_gpickle()" is no longer avaliable.
This should help new users to get up and running.
