### ISSUE TITLE
smile2cg division by 0 error for PL PEI

### ISSUE THREAD

**Issue by santamaria42** [subhamoymahajan/Martini_PEI_ff#3]
# Description
smile2cg "ssqssssssqsssspq" ... gives the following error:
`/coarsen/smile.py", line 94, in smile2top
    ': ' + str(round(Ntsp[1]/Ntsp[0],2)) + ': 1')
ZeroDivisionError: division by zero`
It seems that since there are no "t" or "tq" beads in the string Ntsp[0] remains at 0 resulting in this error.

**Comment by subhamoymahajan** [comment]
It  should be fixed now. Please have a look.

**Comment by santamaria42** [comment]
Yes it works now. Thank you.
